// DO NOT EDIT — generated by concept/03-orm-schema/codegen/diagram-to-drizzle.ts from concept/02-diagram/schema.nesycat.json.
// Edit the diagram, then run: npm run db:diagram

import { pgTable, uuid, text, jsonb, timestamp, pgPolicy } from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'
import { authenticatedRole, authUid } from 'drizzle-orm/supabase'

export const diagrams = pgTable(
  'diagrams',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    ownedBy: uuid('owned_by').notNull(),
    title: text('title').notNull(),
    data: jsonb('data').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    pgPolicy('diagrams_select_own', { for: 'select', to: authenticatedRole, using: sql`${t.ownedBy} = ${authUid}` }),
    pgPolicy('diagrams_insert_own', { for: 'insert', to: authenticatedRole, withCheck: sql`${t.ownedBy} = ${authUid}` }),
    pgPolicy('diagrams_update_own', { for: 'update', to: authenticatedRole, using: sql`${t.ownedBy} = ${authUid}`, withCheck: sql`${t.ownedBy} = ${authUid}` }),
    pgPolicy('diagrams_delete_own', { for: 'delete', to: authenticatedRole, using: sql`${t.ownedBy} = ${authUid}` }),
  ],
)

export type Diagram = typeof diagrams.$inferSelect
export type NewDiagram = typeof diagrams.$inferInsert
